const projectsData = [
  {
    id: 1,
    title: "This React Portfolio Website",
    description: "Project 1 description",
    image: "/images/projects/MyPortfolioScreenShot.png",
    tag: ["All", "Web", "React", "TailwindCSS", "Docker", "AWS Amplify"],
    gitUrl: "https://github.com/hurstcorey/MyPortfolioSite",
    previewUrl: "/",
  },
  {
    id: 2,
    title: "Fate RRPG React Native App",
    description: "Project 2 description",
    image: "",
    tag: ["All", "Mobile", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 3,
    title: "Blog Website",
    description: "My Personal Blog where I talk about my life, experiences, and interest",
    image: "/images/projects/Coreyblog.png",
    tag: ["All", "blog", "Web", "Google Blogs"],
    gitUrl: "https://support.google.com/blogger/answer/1623800?hl=en",
    previewUrl: "https://blog.cohurst.co/",
  },
  {
    id: 4,
    title: "MyAssistant PWA App",
    description: "Project 4 description",
    image: "",
    tag: ["All", "Mobile", "AI Chatbot", "Machine Learning", "ReactNative", "Node.js", "TailwindCSS", "Docker", "Localhosted", "Tailscale", "Ollama"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 5,
    title: "Star Wars Unlimited App",
    description: "A feature-rich implementation of the Star Wars Unlimited TCG, enabling deck building and gameplay against an AI opponent.",
    image: "/images/projects/star-wars-unlimited.png",
    tag: ["All", "Web", "Mobile", "PWA", "Vite", "Express", "React", "Node.js", "TailwindCSS", "Drizzle", "Docker", "Replit"],
    gitUrl: "/",
    previewUrl: "/swu",
  },
  {
    id: 6,
    title: "AI Diagram Generator",
    description: "An AI-powered tool to create diagrams from text descriptions.",
    image: "/images/projects/ai-diagram-generator.png",
    tag: ["All", "Web", "AI", "Replit"],
    gitUrl: "/",
    previewUrl: "https://diagram-master-ai-coreyhurst88.replit.app/",
  },
];

export default projectsData;
